import type { DebsProps } from "./types/transaction";

export const DebsData: DebsProps[] = [
  {
    id: 1,
    tgl_transaksi: "2023-01-15",
    jatuh_tempo: "2023-02-15",
    akun: "Bank ABC",
    mitra: "PT. XYZ",
    status: "lunas",
    keterangan: "Pembayaran invoice #1234",
    bukti: "bukti_pembayaran_1234.jpg",
    jumlah: 1500000,
    sisa: 0,
  },
  {
    id: 2,
    tgl_transaksi: "2023-01-20",
    jatuh_tempo: "2023-02-20",
    akun: "Dompet Digital DEF",
    mitra: "CV. MNO",
    status: "berjalan",
    keterangan: "Pembayaran jasa konsultasi",
    bukti: "bukti_pembayaran_konsultasi.jpg",
    jumlah: 750000,
    sisa: 500000,
  },
  {
    id: 3,
    tgl_transaksi: "2023-01-25",
    jatuh_tempo: "2023-02-25",
    akun: "Kartu Kredit GHI",
    mitra: "PT. PQR",
    status: "berjalan",
    keterangan: "Pembayaran pembelian alat tulis kantor",
    bukti: "bukti_pembayaran_alat_tulis.jpg",
    jumlah: 300000,
    sisa: 200000,
  },
  {
    id: 4,
    tgl_transaksi: "2023-01-30",
    jatuh_tempo: "2023-02-28",
    akun: "Rekening Tabungan JKL",
    mitra: "UD. STU",
    status: "jatuh tempo",
    keterangan: "Pembayaran sewa kantor bulan Januari",
    bukti: "bukti_pembayaran_sewa_januari.jpg",
    jumlah: 2000000,
    sisa: 500000,
  },
  {
    id: 5,
    tgl_transaksi: "2023-02-05",
    jatuh_tempo: "2023-03-05",
    akun: "E-Wallet MNO",
    mitra: "PT. VWX",
    status: "lunas",
    keterangan: "Pembayaran iklan online",
    bukti: "bukti_pembayaran_iklan.jpg",
    jumlah: 500000,
    sisa: 0,
  },
];
