import { type TableProps } from "./partials/columns";

export const data: TableProps[] = [
  {
    id: 1,
    date: "2023-01-01",
    account: "BNI - Kas",
    type: "Pemasukan",
    category: "Transportasi",
    note: "Terima Dana",
    file: "",
    amount: 500000,
  },
  {
    id: 2,
    date: "2023-01-01",
    account: "BNI - Kas",
    type: "Pengeluaran",
    category: "Makan",
    note: "Makan Siang",
    file: "",
    amount: 250000,
  },
  {
    id: 3,
    date: "2023-01-01",
    account: "BNI - Kas",
    type: "Pindah Dana",
    category: "-",
    note: "Pindah Saldo Akun",
    file: "",
    amount: 300000,
  },
  {
    id: 4,
    date: "2023-01-01",
    account: "BNI - Kas",
    type: "Piutang",
    category: "Administrasi",
    note: "Terima dana",
    file: "",
    amount: 300000,
  },
  {
    id: 5,
    date: "2023-01-01",
    account: "BNI - Kas",
    type: "Hutang",
    category: "Administrasi",
    note: "Terima Dana",
    file: "",
    amount: 100000,
  },
  {
    id: 6,
    date: "2023-01-01",
    account: "Cash",
    type: "Pengeluaran",
    category: "Pembayaran",
    note: "Pembayaran bulan januari",
    file: "",
    amount: 100000,
  },
  {
    id: 7,
    date: "2023-01-01",
    account: "Cash",
    type: "Pengeluaran",
    category: "Pembayaran",
    note: "Pembayaran bulan januari",
    file: "",
    amount: 100000,
  },
  {
    id: 8,
    date: "2023-01-01",
    account: "Cash",
    type: "Pengeluaran",
    category: "Pembayaran",
    note: "Pembayaran bulan januari",
    file: "",
    amount: 100000,
  },
  {
    id: 9,
    date: "2023-01-01",
    account: "Cash",
    type: "Pengeluaran",
    category: "Pembayaran",
    note: "Pembayaran bulan januari",
    file: "",
    amount: 100000,
  },
  {
    id: 10,
    date: "2023-01-01",
    account: "Cash",
    type: "Pengeluaran",
    category: "Pembayaran",
    note: "Pembayaran bulan januari",
    file: "",
    amount: 100000,
  },
  {
    id: 11,
    date: "2023-01-01",
    account: "Cash",
    type: "Pengeluaran",
    category: "Pembayaran",
    note: "Pembayaran bulan januari",
    file: "",
    amount: 100000,
  },
  {
    id: 12,
    date: "2023-01-01",
    account: "Cash",
    type: "Pengeluaran",
    category: "Pembayaran",
    note: "Pembayaran bulan januari",
    file: "",
    amount: 100000,
  },
  {
    id: 13,
    date: "2023-01-01",
    account: "Cash",
    type: "Pengeluaran",
    category: "Pembayaran",
    note: "Pembayaran bulan januari",
    file: "",
    amount: 100000,
  },
  {
    id: 14,
    date: "2023-01-01",
    account: "Cash",
    type: "Pengeluaran",
    category: "Pembayaran",
    note: "Pembayaran bulan januari",
    file: "",
    amount: 100000,
  },
  {
    id: 15,
    date: "2023-01-01",
    account: "Cash",
    type: "Pengeluaran",
    category: "Pembayaran",
    note: "Pembayaran bulan januari",
    file: "",
    amount: 100000,
  },
  {
    id: 16,
    date: "2023-01-01",
    account: "Cash",
    type: "Pengeluaran",
    category: "Pembayaran",
    note: "Pembayaran bulan januari",
    file: "",
    amount: 100000,
  },
  {
    id: 17,
    date: "2023-01-01",
    account: "Cash",
    type: "Pengeluaran",
    category: "Pembayaran",
    note: "Pembayaran bulan januari",
    file: "",
    amount: 100000,
  },
];
